class Api::V1::PropertyInformationSerializer < Api::V1::ApplicationSerializer
    attributes  :id,
                :property_id,
                :name,
                :tipo,
                :superficie,
                :address,
                :english_name,
                :park_property,
                :region,
                :market,
                :industry,
                :suprficie_total,
                :superficie_urbanizada,
                :superficie_disponible,
                :inicio_de_operaciones,
                :number_employe,
                :practices_recognition,
                :infrastructure,
                :navy_number,
                :message,
                :postal_code,
                :colony,
                :municipality,
                :state,
                :status,
                :unity,
                :created_at,
                :updated_at,
                :lat, 
                :lng,
                :num_int,
                :num_ext,
                :phone,
                :lada,
                :code

    has_many :property
    has_many :status_disponibilities
end
